spring:
  application:
    name: customer-service
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  datasource:
    initialization-mode: always
server:
  port: 8085
eureka:
  instance:
    preferIpAddress: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  cloudfoundry:
    skip-ssl-validation: true
    enabled: true